### ISSUE TITLE
merging `many` accessors

### ISSUE THREAD

**Issue by ghennequin** [janestreet/accessor#1]
I have been trying to merge a list of `(_ -> 'a -> 'b, _ -> 'a t -> 'b t, [< many ]) Accessor.t` accessors (assumed to not overlap, i.e. access different elements) into a single accessor of the same type that accesses all the elements at once. For example:

```ocaml
type 'a t =
   { x : 'a
   ; y : 'a List.t
   ; z : int
   }
[@@deriving accessors]

(* assuming I have successfully implemented this [merge] function: *)
let all_a = merge [ x; y @> Accessor.List.each ]
```

In this particular example I suppose I could do this manually as follows:

```ocaml
let merged : (_ -> 'a -> 'b, _ -> 'a t -> 'b t, [< many ]) Accessor.t =
    [%accessor
      Accessor.many (fun r ->
          let open Accessor.Many.Let_syntax in
          let%map_open x = access r.x
          and y = Accessor.Many.all (List.map x.y ~f:access) in
          { r with x; y })]
```

but is there a way of writing a more generic `merge` function? E.g. if the `y` field was an `'a Array.t` instead of a `'a List.t`, the above wouldn't work.

**Comment by jakemcarthur** [comment]
It's implementable, but it won't have the nice polymorphic type that your custom function has. In particular, your `x` and `y @> Accessor.List.each` accessors cannot change the type parameter of your `t`, so the merged accessor won't be able to either. It also, as you already mentioned, requires its input accessors not to overlap. Supposing we are okay with that, here is a kind of an inefficient way to do it.

    let field_product t1 t2 =
      Accessor.field
        ~get:(fun x -> x.@(t1), x.@(t2))
        ~set:(fun x (a, b) -> (x.@(t1) <- a).@(t2) <- b)
    
    let merge t1 t2 =
      field_product (Accessor.many_to_list_field t1) (Accessor.many_to_list_field t2)
      @> Accessor.Tuple2.each
      @> Accessor.List.each

The above functions have the following types:

    val field_product
      :  (unit, 'a, 'c, [> field ]) Accessor.t
      -> (unit, 'b, 'c, [> field ]) Accessor.t
      -> (_, 'a * 'b, 'c, [< field ]) Accessor.t
    
    val merge
      :  (unit, 'a, 'b, [> many ]) Accessor.t
      -> (unit, 'a, 'b, [> many ]) Accessor.t
      -> (_, 'a, 'b, [< many ]) Accessor.t

I'll add these functions in some form. If you can think of a nicer or more general way to implement them, that'd be cool, but my feeling is that this is about as good as it gets.
